services:
  - type: web
    name: sportflix-api
    env: node
    rootDir: server
    buildCommand: npm install && npx prisma migrate deploy && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        value: file:./prisma/dev.db
